db.getCollection('Hupe').find({Nome:"ELIZABETH CORREA DE SOUZA"})

db.getCollection('Hupe').find({Nome:{ $regex : "CELESTINO" }})

db.getCollection('Hupe').find({Nome:{ $in: [ 
    'ADENAIR MOREIRA DALGOBBO',
    'AMERICO ALVES LEONARDO',
    'ANTONIO JOSE DE BARROS',
    'ARLETE FERNANDES MARTINS COST',
    'CELESTINO CAMPOS DA SILVA NETO',
    'CELIA REGINA AZEVEDO BUENO',
    'CINESIO CUSTODIO LOPRES',
    'CLARA CASTRO MICHELI',
    'CLAUDIA GONZE CORTES',
    'DILMA RODRIGUES DE SOUZA SILVA',
    'DOMINGOS RAIMUNDO DOS SANTOS',
    'EDIMAR CORREIA DIAS',
    'ELIZABETH CORREA DE SOUZA',
    'ELIZETE GUEDES DA SILVA',
    'ESTHER DE SOUZA CORDEIRO VITORINO',
    'FRANCISCO DAS CHAGAS PAIVA DE OLIVEIRA',
    'FRANCISCO MELO DA SILVA',
    'IVANILDA BALBINA DE SOUZA',
    'JOANA MOREIRA DOS SANTOS',
    'JOAO LOURENÇO DA SILVA FILHO',
    'JOSE CARLOS PEREIRA DA SILVA',
    'JOSE FERREIRA WERNECK',
    'LIGIA DA SILVA BARBOSA',
    'LUIZ DE SOUZA',
    'MARIA APARECIDA MELO DOS SANTOS',
    'MARIA DA GRACA ARANHA VIEIRA',
    'MARIA DO CARMO PEREIRA BARBOSA',
    'MARIA JOSE ANDRADE ALVES',
    'MARIA JOSÉ ANDRADE ALVES',
    'MARIA LUZIA DOS SANTOS',
    'NARCISO FRANCISCO DE OLIVEIRA',
    'OSEAS VENTURA',
    'OZARENA LUZIA CAMPOS BEZERRA',
    'ROSÂNGELA DE OLIVEIRA MARQUES',
    'ROSANGELA SARDINHA DE ABREU',
    'ROSINEIDE MARIA DE OLIVEIRA',
    'SANDRA MARIA SANTOS DIAS',
    'SOLANGE MARINHO VICENTE DA SILVA',
    'SONIA MARIA ESTEVAO VIEIRA',
    'VERA LUCIA TEIXEIRA PECENE',
    'WALDIR DA SILVA PANZA'  ] }}).sort({Nome: 1});